// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bsa2018_ProjectStructure.DataAccess.Model;

namespace bsa2018ProjectStructure.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180714161115_AddAttributes")]
    partial class AddAttributes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("bsa2018_ProjectStructure.DataAccess.Model.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdAircraftType");

                    b.Property<TimeSpan>("LifeSpan");

                    b.Property<string>("Name")
                        .HasMaxLength(15);

                    b.Property<DateTime>("ReleaseDate");

                    b.HasKey("Id");

                    b.HasIndex("IdAircraftType")
                        .IsUnique();

                    b.ToTable("Aicrafts");
                });

            modelBuilder.Entity("bsa2018_ProjectStructure.DataAccess.Model.AircraftType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("LoadCapacity");

                    b.Property<int>("Places");

                    b.HasKey("Id");

                    b.ToTable("AircraftTypes");
                });

            modelBuilder.Entity("bsa2018_ProjectStructure.DataAccess.Model.Crew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdPilot");

                    b.HasKey("Id");

                    b.HasIndex("IdPilot");

                    b.ToTable("Crews");
                });

            modelBuilder.Entity("bsa2018_ProjectStructure.DataAccess.Model.Departure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DepartureTime");

                    b.Property<int>("IdAircraft");

                    b.Property<int>("IdCrew");

                    b.Property<int>("IdFlight");

                    b.HasKey("Id");

                    b.HasIndex("IdAircraft");

                    b.HasIndex("IdCrew");

                    b.HasIndex("IdFlight");

                    b.ToTable("Departures");
                });

            modelBuilder.Entity("bsa2018_ProjectStructure.DataAccess.Model.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ArrivalTime");

                    b.Property<string>("DeparturePlace")
                        .IsRequired();

                    b.Property<DateTime>("DepartureTime");

                    b.Property<string>("Destination")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("bsa2018_ProjectStructure.DataAccess.Model.Pilot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday");

                    b.Property<int>("Experience");

                    b.Property<string>("Name")
                        .HasMaxLength(20);

                    b.Property<string>("Surname")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Pilots");
                });

            modelBuilder.Entity("bsa2018_ProjectStructure.DataAccess.Model.Stewardess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Name")
                        .HasMaxLength(20);

                    b.Property<string>("Surname")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Stewardess");
                });

            modelBuilder.Entity("bsa2018_ProjectStructure.DataAccess.Model.StewardessCrew", b =>
                {
                    b.Property<int>("IdStewardess");

                    b.Property<int>("IdCrew");

                    b.HasKey("IdStewardess", "IdCrew");

                    b.HasIndex("IdCrew");

                    b.ToTable("StewardessCrew");
                });

            modelBuilder.Entity("bsa2018_ProjectStructure.DataAccess.Model.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Cost");

                    b.Property<int>("IdFlight");

                    b.HasKey("Id");

                    b.HasIndex("IdFlight");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("bsa2018_ProjectStructure.DataAccess.Model.Aircraft", b =>
                {
                    b.HasOne("bsa2018_ProjectStructure.DataAccess.Model.AircraftType", "AircraftType")
                        .WithOne("Aircraft")
                        .HasForeignKey("bsa2018_ProjectStructure.DataAccess.Model.Aircraft", "IdAircraftType")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bsa2018_ProjectStructure.DataAccess.Model.Crew", b =>
                {
                    b.HasOne("bsa2018_ProjectStructure.DataAccess.Model.Pilot", "Pilot")
                        .WithMany("Crews")
                        .HasForeignKey("IdPilot")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bsa2018_ProjectStructure.DataAccess.Model.Departure", b =>
                {
                    b.HasOne("bsa2018_ProjectStructure.DataAccess.Model.Aircraft", "Aircraft")
                        .WithMany("Departures")
                        .HasForeignKey("IdAircraft")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("bsa2018_ProjectStructure.DataAccess.Model.Crew", "Crew")
                        .WithMany("Departures")
                        .HasForeignKey("IdCrew")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("bsa2018_ProjectStructure.DataAccess.Model.Flight", "Flight")
                        .WithMany("Departures")
                        .HasForeignKey("IdFlight")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bsa2018_ProjectStructure.DataAccess.Model.StewardessCrew", b =>
                {
                    b.HasOne("bsa2018_ProjectStructure.DataAccess.Model.Crew", "Crew")
                        .WithMany("StewardessCrews")
                        .HasForeignKey("IdCrew")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("bsa2018_ProjectStructure.DataAccess.Model.Stewardess", "Stewardess")
                        .WithMany("StewardessCrews")
                        .HasForeignKey("IdStewardess")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bsa2018_ProjectStructure.DataAccess.Model.Ticket", b =>
                {
                    b.HasOne("bsa2018_ProjectStructure.DataAccess.Model.Flight", "Flight")
                        .WithMany("Tickets")
                        .HasForeignKey("IdFlight")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
